# Site Settings
title: Nikolay Dimitrow
email: nikidimitrow@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Nikolay Dimitrow. Portfolio and Blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nikidimitrow.com" # the base hostname & protocol for your site

# Theme Settings
remote_theme: "BDHU/minimalist"
color-scheme: dark 
logo: "/assets/images/logo_nikidimitrow.png" 

# Sidebar Settings (This creates the links on the left)
github_username: nikidimitrow

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
